export default function getAllProducts() {
  return [
    {
      id: 'ECO-HS-001',
      slug: 'eco-house-001',
      name: 'Apartment JKT Living Star',
      category: 'House',
      categorySlug: 'house',
      price: 950_571_000,
      stock: 100,
      imageUrl: '/assets/img/1home.jpg',
      description: `JKT Living Star is a contemporary apartment complex situated in the heart of Jakarta, providing convenient access to urban conveniences. The aesthetic appeal and functional design of the complex include a variety of unit types, well-suited for families and young professionals.
                        Each unit is furnished with high-quality items and features large windows that allow for the entry of natural light. Residents have access to a swimming pool, a gym, and green spaces, conducive to relaxation. The complex is situated in a location that is convenient for shopping, dining, and public transportation,
                        making it an ideal choice for individuals who desire a vibrant urban lifestyle. Additionally, the complex provides 24-hour security and attentive service, which contribute to a comfortable and secure living experience.`,
      rating: 3.0,
    },
    {
      id: 'EC0-HS-002',
      slug: 'eco-house-002',
      name: 'Lavia Living, Jakarta',
      category: 'House',
      categorySlug: 'house',
      price: 2_186_313_300,
      stock: 5,
      imageUrl: '/assets/img/2home.jpg',
      description: `The Lavia Living Type 5 in Citra Garden City, Jakarta, is a modern residence designed for comfort and functionality. With a land area of 60 m² and a building area of 95 m², it features four bedrooms and three bathrooms, making it ideal for families. The stylish interior, crafted from high-quality materials, creates a warm atmosphere.
                    Citra Garden City is known for its aesthetic appeal and extensive amenities, including green spaces and convenient access to shopping and transport. The residence is equipped with an advanced security system, ensuring the safety of its occupants. Overall, Lavia Living Type 5 is an excellent choice for quality housing in Jakarta.`,
      rating: 4.0,
    },
    {
      id: 'ECO-HS-003',
      slug: 'eco-house-003',
      name: 'Avilla Nova Cluster ',
      category: 'House',
      categorySlug: 'house',
      price: 1_017_111_000,
      stock: 5,
      imageUrl: '/assets/img/3home.jpg',
      description: `The Avilla Nova cluster at Samanea Hill is a modern residential development that blends comfort with aesthetic appeal. It features various architectural styles designed for families, with spacious interiors and abundant natural light, enhanced by premium materials.
                    Located strategically, Samanea Hill offers easy access to shopping centers, schools, and recreational areas. Surrounded by lush green parks, the cluster provides a tranquil atmosphere. With a secure environment and a friendly community, Avilla Nova is an excellent choice for quality housing in a thriving area.`,
      rating: 3.0,
    },
    {
      id: 'ECO-HS-004',
      slug: 'eco-house-004',
      name: 'Quantis Signature at BSD City',
      category: 'House',
      categorySlug: 'house',
      price: 8_150_659_350,
      stock: 5,
      imageUrl: '/assets/img/4home.jpg',
      description: `The Quantis Signature Type 178 in BSD City is a modern residence tailored for families. With a built-up area of 178 m², it features three bedrooms and two bathrooms, ensuring spacious and comfortable living. The sophisticated interior and high-quality materials create a warm atmosphere.
                    Located in the rapidly developing BSD City, the home offers easy access to shopping, schools, and recreational facilities. Its attractive, secure environment, supported by a robust security system, makes Quantis Signature Type 178 an excellent choice for those seeking a premium residence in a vibrant urban setting.`,
      rating: 5.0,
    },

    {
      id: 'EC0-MT-005',
      slug: 'eco-material-005',
      name: 'Bamboo Petung ',
      category: 'Material',
      categorySlug: 'material',
      price: 4_199_850,
      stock: 0,
      imageUrl: '/assets/img/image 40.png',
      description: `Bamboo Petung (Dendrocalamus asper) is an optimal choice for those who prioritize sustainability and environmental responsibility. As one of the largest and strongest bamboos, Bamboo Petung offers exceptional strength, durability, and the ability to be harvested sustainably. Its rapid growth also makes it an ideal choice for construction, furniture, and decoration projects. By using Bamboo Petung, you can support eco-friendly practices that reduce deforestation and carbon emissions.`,
      rating: 3.0,
    },
    {
      id: 'ECO-MT-006',
      slug: 'eco-material-006',
      name: 'Eiken (Oak) ',
      category: 'Material',
      categorySlug: 'material',
      price: 24_886_650,
      stock: 0,
      imageUrl: '/assets/img/image 52.png',
      description: `Eiken (Oak) - Tongue and Groove is the optimal choice for those seeking natural beauty and exceptional durability in their building projects. This oak offers an elegant aesthetic with a tongue and groove system that ensures easy and sturdy installation, and it is sourced from a sustainably managed source. By selecting Eiken (Oak), you are supporting environmentally friendly practices that help preserve forests and reduce carbon footprints. Additionally, oak is renowned for its high resistance to wear and tear, making it an optimal choice for long-lasting flooring and wall panels. Make Eiken (Oak) - Tongue and Groove part of your green solution for your home or project, and enjoy the long-term benefits of this high-quality material.`,
      rating: 4.0,
    },
    {
      id: 'ECO-MT-007',
      slug: 'eco-material-007',
      name: 'Basaltic Rock ',
      category: 'Material',
      categorySlug: 'material',
      price: 1_909_000,
      stock: 0,
      imageUrl: '/assets/img/image 58.png',
      description: `Basalt rock is the optimal choice for your construction projects that require exceptional strength and durability. Formed from natural volcanic processes, this rock has a dense and hard structure, making it highly resistant to pressure and erosion. Additionally, basalt rock is an eco-friendly material, derived from an abundant and renewable natural resource. By choosing basalt rock, you are not only getting a durable and strong material, but also contributing to the preservation of the environment. Make basalt rock a part of your construction solution for optimal and sustainable results.`,
      rating: 5.0,
    },
    {
      id: 'ECO-MT-008',
      slug: 'eco-material-009',
      name: 'Plastic Waste Recycling Paving Block ',
      category: 'Material',
      categorySlug: 'material',
      price: 1_909_000,
      stock: 0,
      imageUrl: '/assets/img/material4_besar.jpg',
      description: `Paving blocks are a great option for landscaping and road projects that need to stand up to a lot of wear and tear and look good doing it. Made from a high-quality concrete mix, paving blocks are strong and can handle heavy loads and extreme weather. Plus, paving blocks come in all kinds of designs and colors, so you can get the look you want. They're also eco-friendly because you can recycle them and they reduce construction waste. When you choose paving blocks, you get a durable and attractive solution that's good for the planet. Make paving blocks part of your construction solution for the best and greenest results.`,
      rating: 3.0,
    },
    {
      id: 'ECO-TC-009',
      slug: 'eco-technology-009',
      name: 'SunPower Maxeon Solar Panels ',
      category: 'Technology',
      categorySlug: 'technology',
      price: 381_603_000,
      stock: 0,
      imageUrl: '/assets/img/prop_1.jpg',
      description: `SunPower Maxeon solar panels offer the highest energy efficiency of up to 22.8%, producing more energy and reducing your carbon footprint. Designed for durability in extreme weather conditions, the panels are backed by up to a 40-year warranty. Its advanced technology reduces corrosion and damage, making it a safe and environmentally friendly long-term investment. With SunPower Maxeon, you can significantly reduce your electricity costs and contribute to a greener environment.`,
      rating: 5.0,
    },
    {
      id: 'ECO-TC-010',
      slug: 'eco-technology-010',
      name: 'Enrave Large Ceiling Lamp ',
      category: 'Technology',
      categorySlug: 'technology',
      price: 4_430_118.75,
      stock: 0,
      imageUrl: '/assets/img/prop_2.jpg',
      description: `Light large rooms like the living room with the Enrave Large Ceiling Lamp. It emits a soft light toward the ceiling and a strong light downward, filling the room with soothing warm to cool tones. With a modern and sleek design, this lamp is not only aesthetically pleasing, but also energy efficient. Using energy-efficient LED technology, it reduces power consumption and carbon footprint, making it a sustainable and environmentally friendly choice with a lifespan of up to 10 years. 
                    Key features include smart control via the Hue app or voice commands with Alexa and Google Assistant, and customizable light with over 50,000 shades of warm to cool white. Choose the Enrave Large Ceiling Lamp for a smart, efficient and eco-friendly lighting solution.`,
      rating: 3.0,
    },
    {
      id: 'ECO-TC-011',
      slug: 'eco-technology-011',
      name: 'Moen Smart Shower 2-Outlet Shower Valve',
      category: 'Technology',
      categorySlug: 'technology',
      price: 10_197_945.75,
      stock: 0,
      imageUrl: '/assets/img/prop_3.jpg',
      description: `Enjoy an extraordinary shower experience with the Nebia by Moen Smart Shower. Using advanced atomization technology, this shower breaks the water into tiny droplets, 
                    giving you the sensation of more water while using up to 45% less water than traditional showers. Its modern and elegant design not only enhances the aesthetics of your bathroom, but is also environmentally friendly, reducing water and energy consumption. With smart control via an app and compatibility with Alexa and Google Assistant, Nebia by Moen offers convenience and efficiency in one package. Choose Nebia by Moen for a luxurious, energy-efficient and sustainable bathroom solution.`,
      rating: 4.0,
    },
    {
      id: 'ECO-TC-012',
      slug: 'eco-technology-013',
      name: 'Google Nest Thermostat E Pro',
      category: 'Technology',
      categorySlug: 'technology',
      price: 12_215_500,
      stock: 0,
      imageUrl: '/assets/img/prop_4.jpg',
      description: `The Nest Thermostat E is a smart thermostat designed to optimize comfort and energy efficiency in your home. With a minimalist and elegant design, this device learns your habits and automatically adjusts the temperature to save energy when you're away. 
                    You can control the temperature from anywhere using the Nest app on your smartphone. The Nest Thermostat E also provides energy usage reports and suggestions for further savings, and it is compatible with various heating and cooling systems. With these features, the Nest Thermostat E is the perfect solution for those looking to enhance energy efficiency in a smart and stylish way.`,
      rating: 3.0,
    },
  ];
}
